config/routes.rb
Movierama::Application.routes.draw do

  root to: 'movies#index'

  resources :users, only: [:create, :show] do
    resources :movies, except: [:index, :show] do
      resources :votes, only: [:create, :destroy]      
    end
  end
  resources :sessions, only: [:create]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include MovieHelper

  before_filter :authenticate, only: [:new, :create]
  before_filter :set_movie, only: [:edit, :update, :destroy]
  before_filter :not_found_unless_own_movie, only: [:edit, :update, :destroy]
  
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(params[:movie])
    @movie.user_id = current_user.id
    if @movie.save
      flash[:success] = 'Movie created successfully'
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    render 'new'
  end

  def update
    if @movie.update_attributes(params[:movie])
      flash[:success] = 'Movie updated'
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def destroy
    @movie.destroy
    flash[:success] = 'Movie Deleted'
    redirect_to user_path(current_user)
  end

  def index
    @movies = order_movies(Movie)
  end

  # -------------- Private -------------------------------------------------
  private

    def set_movie
      @movie = Movie.find(params[:id])
    end

    def not_found_unless_own_movie
      not_found unless (signed_in? && current_user == @movie.user)
    end
end

app/views/movies/_movie_item.html.erb
<div class="movie-box">
  <%= render 'shared/error_messages', obj: movie %>
  <span class="movie-title"><%= movie.title %></span>

  <br>

  Posted by <%= link_to movie.user.name, user_path(movie.user) %> <%= time_ago_in_words(movie.created_at) %> ago

  <br><br>

  <div>
    <%= movie.description %>
  </div>

  <br>

  <%= render partial: 'movies/vote_section', locals: { movie: movie } %>
  
</div>
<br>

app/views/movies/_vote_section.html.erb
<div class="vote-section">
  <% likes_count = movie.likes_count %>
  <% hates_count = movie.hates_count %>
  
  <!-- Instead of link for voting/unvoting, there is a span that has for attributes the url and method of its associated action. These two attributes are parsed by the jQuery code, which extracts them, in order to make these actions -->

  <div class="span-8">
    <%= "Be the first to vote for this movie:" if (movie.votes.count == 0 && signed_in? && !own_movie?(movie)) %>
      <%= !signed_in? || own_movie?(movie) || liked_movie?(movie) ? pluralize(likes_count, 'like') : "<span class='vote-link' data-url=#{user_movie_votes_path(movie.user, movie, vote: true)} data-method='POST'>#{pluralize(likes_count, 'like')}</span>".html_safe %>
    |
    <%= !signed_in? || own_movie?(movie) || hated_movie?(movie) ? pluralize(hates_count, 'hate') : "<span class='vote-link' data-url=#{user_movie_votes_path(movie.user, movie, vote: false)} data-method='POST'>#{pluralize(hates_count, 'hate')}</span>".html_safe %>
  </div>

  <% if v= (liked_movie?(movie) || hated_movie?(movie)) %>
    <div class="span-7 last tar">
      <% kind = kind_of_vote(movie) %>
      You <%= kind %> this movie | <%= "<span class='vote-link' data-url=#{user_movie_vote_path(movie.user, movie.id, v.id)} data-method='DELETE'>Un#{kind}</span>".html_safe %>
    </div>
  <% end %>

  <% if signed_in? && own_movie?(movie) %>
    <div class="span-7 last tar">
      <%= link_to "Edit", edit_user_movie_path(movie.user, movie.id) %> | <%= link_to "Delete", user_movie_path(movie.user, movie.id), method: :delete %>
    </div>
  <% end %>

  <div class="clear"></div>
</div>

app/views/movies/index.html.erb
<h1>All the Movies</h1>
<%= render partial: 'layouts/order_bar' %>

<%= render partial: 'movie_item', collection: @movies, as: :movie %>

<div class="tac">
  <%= will_paginate @movies %>
</div>

app/views/movies/new.html.erb
<h1><%= params[:action] == 'new' ? "Add new Movie" : "Edit Movie" %></h1>
<div class="span-10">
  <%= form_for(@movie, url: params[:action] == 'new' ? user_movies_path(current_user) : user_movie_path(current_user, @movie)) do |f| %>
    <%= render 'shared/error_messages', obj: f.object %>
    <div class="field">
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %> 
    </div>
    <div class="field">
      <%= f.label :description %>
      <br>
      <%= f.text_area :description %> 
    </div>
    <br>
    <%= f.submit params[:action] == 'new' ? "Create Movie" : "Update Movie" %>
  <% end %>
</div>