config/routes.rb
Movierama::Application.routes.draw do

  root to: 'movies#index'

  resources :users, only: [:create, :show] do
    resources :movies, except: [:index, :show] do
      resources :votes, only: [:create, :destroy]      
    end
  end
  resources :sessions, only: [:create]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/views/layouts/_application_stage_header.html.erb
<% unless flash.empty? %>
  <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="span-8">
  <h1><%= link_to "MovieRama", root_path, id: 'logo-text' %></h1>
</div>

<div class="span-16 prepend-top last tar">
  <% if signed_in? %>
    Welcome back <%= link_to current_user.name, current_user %>
    &nbsp&nbsp&nbsp&nbsp&nbsp
    <%= link_to "Sign out", signout_path, method: :delete %>
  <% else %>
    <%= link_to "Login", signin_path %> or <%= link_to "Sign Up", signup_path %>
  <% end %>
</div>

<hr class="space">

app/views/layouts/_order_bar.html.erb
<div id="order-bar">
  Sort by: 
  <%= link_to "Date", params[:controller] == 'movies' ? root_path(order: 'date') : user_path(params[:id], order: 'date') %> | 
  <%= link_to "Likes", params[:controller] == 'movies' ? root_path(order: 'likes') : user_path(params[:id], order: 'likes') %> | 
  <%= link_to "Hates", params[:controller] == 'movies' ? root_path(order: 'hates') : user_path(params[:id], order: 'hates') %> 
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movierama</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main_page">
    <%= render partial: 'layouts/header' %>

    <%= render 'layouts/application_stage_header' %>
    <div class="span-16">
      <%= yield %>
    </div>

    <% if signed_in?  %>
      <div class="span-8 tac last">
        <%= link_to "New Movie", new_user_movie_path(current_user), class: "btn-01 btn-01-green" %>
      </div>
    <% end %>
  </div>

</body>
</html>